import type { NavItem, WorkflowStage } from '@/types'

export const APP_NAME = 'ZENTROROX'

export const WORKFLOW_STAGES: Omit<WorkflowStage, 'status'>[] = [
  { id: 'booking', label: 'Booking', path: 'booking' },
  { id: 'pickup', label: 'Pickup', path: 'pickup' },
  { id: 'arrival', label: 'Arrival', path: 'gate-in' },
  { id: 'inventory', label: 'Inventory', path: 'receiving' },
  { id: 'voc', label: 'VOC', path: 'voc' },
  { id: 'inspection', label: 'Inspection', path: 'inspection' },
  { id: 'diagnosis', label: 'Diagnosis', path: 'diagnosis' },
  { id: 'estimate', label: 'Estimate', path: 'estimate' },
  { id: 'approval', label: 'Approval', path: 'approval' },
  { id: 'job_card', label: 'Job Card', path: 'job-card' },
  { id: 'assignment', label: 'Assignment', path: 'assignment' },
  { id: 'bay', label: 'Bay', path: 'bay' },
  { id: 'wip', label: 'WIP', path: 'wip' },
  { id: 'qc', label: 'QC', path: 'qc' },
  { id: 'road_test', label: 'Road Test', path: 'road-test' },
  { id: 'invoice', label: 'Invoice', path: 'invoice' },
  { id: 'payment', label: 'Payment', path: 'payment' },
  { id: 'gatepass', label: 'Gatepass', path: 'gatepass' },
  { id: 'delivery', label: 'Delivery', path: 'delivery' },
  { id: 'feedback', label: 'Feedback', path: 'feedback' },
  { id: 'psf', label: 'PSF', path: 'psf' },
]

export const SIDEBAR_NAV: NavItem[] = [
  { label: 'Dashboard', path: '/app/dashboard', icon: 'LayoutDashboard' },
  {
    label: 'Workshop',
    icon: 'Wrench',
    children: [
      { label: 'Bookings', path: '/app/workshop/bookings' },
      { label: 'Pickup', path: '/app/workshop/pickup' },
      { label: 'Gate-In', path: '/app/workshop/gate-in' },
      { label: 'Vehicle Receiving', path: '/app/workshop/receiving' },
      { label: 'VOC', path: '/app/workshop/voc' },
      { label: 'Inspection', path: '/app/workshop/inspection' },
      { label: 'Diagnosis', path: '/app/workshop/diagnosis' },
      { label: 'Estimates', path: '/app/workshop/estimates' },
      { label: 'Approvals', path: '/app/workshop/approvals' },
      { label: 'Job Cards', path: '/app/workshop/job-cards' },
      { label: 'Workshop Floor', path: '/app/workshop/floor' },
      { label: 'Bay Board', path: '/app/workshop/bay-board' },
      { label: 'Technician Board', path: '/app/workshop/technician-board' },
      { label: 'WIP', path: '/app/workshop/wip' },
      { label: 'QC', path: '/app/workshop/qc' },
      { label: 'Road Test', path: '/app/workshop/road-test' },
      { label: 'Delivery', path: '/app/workshop/delivery' },
    ],
  },
  {
    label: 'Parts',
    icon: 'Package',
    children: [
      { label: 'Parts Dashboard', path: '/app/parts/dashboard' },
      { label: 'Parts Master', path: '/app/parts/master' },
      { label: 'Stock', path: '/app/parts/stock' },
      { label: 'Requisition', path: '/app/parts/requisition' },
      { label: 'Issue', path: '/app/parts/issue' },
      { label: 'Return', path: '/app/parts/return' },
      { label: 'OTC Sales', path: '/app/parts/otc-sales' },
      { label: 'Stock Transfer', path: '/app/parts/stock-transfer' },
      { label: 'Stock Adjustment', path: '/app/parts/stock-adjustment' },
      { label: 'Physical Verification', path: '/app/parts/physical-verification' },
    ],
  },
  {
    label: 'Purchase',
    icon: 'ShoppingCart',
    children: [
      { label: 'Purchase Requisition', path: '/app/purchase/requisition' },
      { label: 'RFQ', path: '/app/purchase/rfq' },
      { label: 'Purchase Order', path: '/app/purchase/purchase-order' },
      { label: 'GRN', path: '/app/purchase/grn' },
      { label: 'Purchase Return', path: '/app/purchase/return' },
      { label: 'Vendor Management', path: '/app/purchase/vendors' },
    ],
  },
  {
    label: 'Sales & Billing',
    icon: 'Receipt',
    children: [
      { label: 'Invoice', path: '/app/billing/invoice' },
      { label: 'Receipts', path: '/app/billing/receipts' },
      { label: 'Credit Notes', path: '/app/billing/credit-notes' },
      { label: 'Outstanding', path: '/app/billing/outstanding' },
      { label: 'Gatepass', path: '/app/billing/gatepass' },
    ],
  },
  {
    label: 'CRM',
    icon: 'Users',
    children: [
      { label: 'Customers', path: '/app/crm/customers' },
      { label: 'Vehicles', path: '/app/crm/vehicles' },
      { label: 'Leads', path: '/app/crm/leads' },
      { label: 'Follow-ups', path: '/app/crm/follow-ups' },
      { label: 'Feedback', path: '/app/crm/feedback' },
      { label: 'PSF', path: '/app/crm/psf' },
      { label: 'Complaints', path: '/app/crm/complaints' },
      { label: 'Service Reminders', path: '/app/crm/service-reminders' },
    ],
  },
  { label: 'Reports', path: '/app/reports', icon: 'BarChart3' },
  { label: 'Masters', path: '/app/masters', icon: 'Database' },
  { label: 'Administration', path: '/app/administration', icon: 'Settings' },
  { label: 'Settings', path: '/app/settings', icon: 'SlidersHorizontal' },
]

export const PUBLIC_NAV = [
  { label: 'Home', href: '/' },
  { label: 'Solutions', href: '/#solutions' },
  { label: 'Features', href: '/#features' },
  { label: 'Pricing', href: '/#pricing' },
  { label: 'About', href: '/#about' },
  { label: 'Contact', href: '/#contact' },
]
