import { DocumentHeader } from './document-header'
import { DocumentFooter } from './document-footer'
import { DocumentLayout } from './document-layout'
import { PrintActions } from './print-actions'
import { useOrganization } from '@/hooks/use-organization'
import { BRAND } from '@/lib/brand'
import { authStorage } from '@/lib/auth-storage'

interface ReportRow {
  metric: string
  value: string | number
}

interface ReportSection {
  title: string
  rows: ReportRow[]
}

interface PrintableReportProps {
  title: string
  sections?: ReportSection[]
  rows?: ReportRow[]
  periodLabel?: string
  generatedAt?: string
}

export function PrintableReport({
  title,
  sections,
  rows,
  periodLabel,
  generatedAt,
}: PrintableReportProps) {
  const { profile } = useOrganization()
  const user = authStorage.getUser()
  const now = generatedAt ?? new Date().toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })

  const allSections: ReportSection[] = sections ?? [{ title: 'Key Performance Indicators', rows: rows ?? [] }]

  return (
    <>
      <PrintActions label="Print Report / Save PDF" />
      <DocumentLayout>
        <DocumentHeader
          title={title}
          subtitle="Management Information System Report"
          documentNo={`RPT-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}`}
          date={now}
          profile={profile}
        />

        <div className="grid grid-cols-3 gap-3 mb-5 text-[10px] border border-brand-border rounded-lg p-3 bg-brand-grey/20">
          <div>
            <p className="text-brand-muted uppercase font-bold tracking-wider">Report Period</p>
            <p className="font-medium mt-0.5">{periodLabel ?? 'Current Session / Live Snapshot'}</p>
          </div>
          <div>
            <p className="text-brand-muted uppercase font-bold tracking-wider">Generated By</p>
            <p className="font-medium mt-0.5">{user ? `${user.firstName} ${user.lastName ?? ''}`.trim() : 'System'}</p>
          </div>
          <div>
            <p className="text-brand-muted uppercase font-bold tracking-wider">Branch</p>
            <p className="font-medium mt-0.5">{profile?.branch?.name ?? 'All Branches'}</p>
          </div>
        </div>

        <div className="print:grid print:grid-cols-2 print:gap-2 print:mb-2">
        {allSections.map((section) => (
          <div key={section.title} className="mb-6 print:mb-0 break-inside-avoid">
            <h2 className="text-xs print:text-[9px] font-bold uppercase tracking-wider text-brand-charcoal border-b border-brand-charcoal pb-1 mb-2 print:mb-1">
              {section.title}
            </h2>
            <table className="w-full text-[11px] print:text-[8px] border-collapse">
              <thead>
                <tr className="bg-brand-charcoal text-white">
                  <th className="text-left px-3 py-1.5 border border-brand-charcoal w-[60%]">Metric</th>
                  <th className="text-right px-3 py-1.5 border border-brand-charcoal">Value</th>
                </tr>
              </thead>
              <tbody>
                {section.rows.map((row, i) => (
                  <tr key={row.metric} className={i % 2 === 0 ? 'bg-white' : 'bg-brand-grey/40'}>
                    <td className="px-3 py-1.5 border border-brand-border">{row.metric}</td>
                    <td className="px-3 py-1.5 border border-brand-border text-right font-semibold">{row.value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
        </div>

        <div className="text-[10px] print:text-[8px] text-brand-muted border border-dashed border-brand-border rounded p-3 mb-4 print:p-2 print:mb-2">
          <p className="font-semibold text-brand-charcoal mb-1">Confidentiality Notice</p>
          <p>This report contains proprietary business information of {profile?.tenant.name ?? BRAND.name}. Unauthorized distribution is prohibited.</p>
        </div>

        <DocumentFooter showSignature={false} terms={[]} copyType="Internal Use" />
      </DocumentLayout>
    </>
  )
}
